# Generated by Django 4.2.3 on 2023-07-22 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='time_added',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='userfood',
            name='time_added',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
