# Generated by Django 4.2.3 on 2023-07-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrient',
            old_name='ntr_code',
            new_name='id',
        ),
    ]
