# Generated by Django 4.0.4 on 2023-06-26 09:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcalorieconversionfactor',
            name='food_nutrient_conversion_factor',
        ),
        migrations.RemoveField(
            model_name='foodfatconversionfactor',
            name='food_nutrient_converter',
        ),
        migrations.RemoveField(
            model_name='foodproteinconversionfactor',
            name='food_nutrient_converter',
        ),
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.ManyToManyField(to='app.foodcategory'),
        ),
        migrations.AddField(
            model_name='foodcalorieconversionfactor',
            name='food_nutrient_cf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_calorie_converter', to='app.foodnutrientconversionfactor'),
        ),
        migrations.AddField(
            model_name='foodfatconversionfactor',
            name='food_nutrient_cf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_fat_converter', to='app.foodnutrientconversionfactor'),
        ),
        migrations.AddField(
            model_name='foodfatconversionfactor',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='foodproteinconversionfactor',
            name='food_nutrient_cf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_protein_converter', to='app.foodnutrientconversionfactor'),
        ),
        migrations.AddField(
            model_name='foodproteinconversionfactor',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 16, 58, 57, 220670)),
        ),
        migrations.AlterField(
            model_name='food',
            name='fdc_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodcalorieconversionfactor',
            name='carbohydrate_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodcalorieconversionfactor',
            name='fat_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodcalorieconversionfactor',
            name='protein_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='food',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_nutrient', to='app.food'),
        ),
        migrations.AlterField(
            model_name='foodnutrientconversionfactor',
            name='food',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_nutrient_converter', to='app.food'),
        ),
        migrations.AlterField(
            model_name='foodportion',
            name='food',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_portion', to='app.food'),
        ),
    ]
