# Generated by Django 4.0.4 on 2023-07-15 05:44

import app.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=datetime.datetime.now)),
                ('expire_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('xp', models.PositiveIntegerField()),
                ('gems', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', app.fields.IntegerRangeField(default=1)),
                ('max_xp', models.PositiveIntegerField(default=0)),
                ('current_xp', models.PositiveIntegerField(default=0)),
                ('gems', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserLevel',
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.ManyToManyField(to='app.difficulty'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='user_rpg',
            field=models.ManyToManyField(to='app.userrpg'),
        ),
    ]
