# Generated by Django 4.0.4 on 2023-06-26 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_foodcalorieconversionfactor_food_nutrient_conversion_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 10, 0, 46, 389813, tzinfo=utc)),
        ),
    ]
