# Generated by Django 4.0.4 on 2023-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_foodnutrientconversionfactor_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodportion',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
