# Generated by Django 4.2.3 on 2023-07-31 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userfood_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfood',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.measureunit'),
        ),
    ]
