# Generated by Django 4.0.4 on 2023-07-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_foodportion_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcalorieconversionfactor',
            name='food_nutrient_cf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_calorie_converter', to='app.foodnutrientconversionfactor'),
        ),
    ]
