# Generated by Django 4.0.4 on 2023-06-26 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dailyentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 10, 18, 24, 259242, tzinfo=utc)),
        ),
    ]
