# Generated by Django 4.2.3 on 2023-07-31 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userfood_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddConstraint(
            model_name='dailyentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='There cant be 2 same daily entries for one user!'),
        ),
    ]
