# Generated by Django 4.0.4 on 2023-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_meal_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.FloatField(choices=[(1, 'None'), (1.2, 'Sedentary'), (1.35, 'Lightly Active'), (1.5, 'Moderately Active'), (1.9, 'Very Active')], default=1),
        ),
    ]
