# Generated by Django 4.0.4 on 2023-06-26 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dailyentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_born',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 11, 10, 36, 886811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 11, 10, 36, 894814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.FloatField(choices=[('1', 'None'), ('1.2', 'Sedentary'), ('1.35', 'Lightly Active'), ('1.5', 'Moderately Active'), ('1.9', 'Very Active')], default='1.2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='body_fat',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=60),
        ),
    ]
