# Generated by Django 4.2.3 on 2023-07-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dailyentry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('sets', models.PositiveSmallIntegerField(verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exercises', to='app.strengthexercise'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
