# Generated by Django 4.2.3 on 2023-07-31 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_strengthexercise_alter_userexercise_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStrengthExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('time_added', models.TimeField(default=datetime.time(0, 0))),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_strength_exercises', to='app.dailyentry')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_strength_exercises', to='app.strengthexercise')),
            ],
        ),
        migrations.DeleteModel(
            name='UserExercise',
        ),
    ]
