# Generated by Django 4.0.4 on 2023-06-27 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_year_born_alter_dailyentry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodportion',
            name='measure_unit_id',
        ),
        migrations.AddField(
            model_name='foodportion',
            name='measure_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_portion', to='app.measureunit'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_born',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
