# Generated by Django 4.0.4 on 2023-06-27 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_foodportion_measure_unit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_food', to=settings.AUTH_USER_MODEL),
        ),
    ]
