# Generated by Django 4.2.3 on 2023-07-31 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_strengthexercise_sets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='foodcategory',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='strengthexercise',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.exercisecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strengthexercise',
            name='difficulty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.exercisedifficulty'),
            preserve_default=False,
        ),
    ]
