# Generated by Django 4.2.3 on 2023-08-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_strengthexercise_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='user',
        ),
        migrations.AddField(
            model_name='challenge',
            name='daily_entry',
            field=models.ManyToManyField(to='app.dailyentry'),
        ),
    ]
